<?php

namespace curlStuff\mTLSclient;

use GuzzleHttp\Client;
use GuzzleHttp\Promise\PromiseInterface;

class mTLSClientExecuteCommands extends Client
{
    public function __construct(array $config = [], array $mtlsOpts = [])
    {
        foreach ($mtlsOpts as $opts => $o){
            $config[$opts] = $o;
        }
        parent::__construct($config);
    }

    public function requestAsync(string $method, $uri = '', array $options = []): PromiseInterface
    {
        return parent::requestAsync($method, $uri, $options); // TODO: Change the autogenerated stub
    }

}