<?php

namespace curlStuff\defaultClient;

use GuzzleHttp\Client;
use Psr\Http\Message\ResponseInterface;

class genericClientValidateHosts extends Client
{
    public function __construct(array $config = [])
    {
        parent::__construct($config);
    }

    public function head($uri, array $options = []): ResponseInterface
    {
        if (is_null(array_key_last($options))){
            $options[] = $this->getConfig();
        }
        return parent::head($uri, $options);
    }

    public function getConfig(string $option = null)
    {
        return parent::getConfig($option); // TODO: Change the autogenerated stub
    }
}